### ISSUE TITLE
Can you help?

### ISSUE THREAD

**Issue by GonsaloFalcaoAgostinho** [BramDC3/smart_duel_disk#8]
I'm from brazil but like yu-gi-oh so when i you're videos i don't believe it and i wanna try so i trying to download the gazer the smart duel disk go but the gazer don't,but the both need downloading again again again and again beacause they reset please can help me?

**Comment by BramDC3** [comment]
Hey, I know you closed the issue, but if you still need help, feel free to ask a question over on Discord. Lots of people there will be able to help you
